// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icxdwtwpfadtcpihhcpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeGR3dHdwZmFkdGNwaWhoY3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjQxMDgsImV4cCI6MjA3MTYwMDEwOH0.qJU5ahwFTAcPHGUnycNmOq6oQA0iB3TWtm38hq3cSRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});